=encoding UTF-8


=head1 NAME

BH_Vec3i - three-dimensional integer vector


=head1 SYNTAX

 #include <BH/Math.h>
 
 cc prog.c -o prog -lbh


=head1 DESCRIPTION

The BH_Vec3i module provides a set of functions for working with 
three-dimensional integer vectors.


=head1 API CALLS


=head2 BH_Vec3iAdd

 void BH_Vec3iAdd(const int a[3],
                  const int b[3],
                  int out[3]);

Calculates the sum of two vectors I<a> and I<b>.

The I<out> parameter describes the resulting vector.


=head2 BH_Vec3iSub

 void BH_Vec3iSub(const int a[3],
                  const int b[3],
                  int out[3]);

Calculates the difference between two vectors I<a> and I<b>.

The I<out> parameter describes the resulting vector.


=head2 BH_Vec3iMul

 void BH_Vec3iMul(const int a[3],
                  const int b[3],
                  int out[3]);

Calculates the result of multiplying two vectors I<a> and I<b>.

The I<out> parameter describes the resulting vector.


=head2 BH_Vec3iScale

 void BH_Vec3iScale(const int a[3],
                    int b,
                    int out[3]);

Calculates the result of multiplying vector I<a> by value I<b>.

The I<out> parameter describes the resulting vector.


=head2 BH_Vec3iMulAdd

 void BH_Vec3iMulAdd(const int a[3],
                     const int b[3],
                     const int c[3],
                     int out[3]);

Calculates the result of the sum I<c> and the result of multiplying vectors 
I<a> and I<b>.

The I<out> parameter describes the resulting vector.


=head2 BH_Vec3iNegate

 void BH_Vec3iNegate(const int in[3],
                     int out[3]);

Calculates the opposite vector from vector I<in>.

The I<out> parameter describes the resulting vector.


=head2 BH_Vec3iMin

 void BH_Vec3iMin(const int a[3],
                  const int b[3],
                  int out[3]);

Calculates the element-wise minimum of two vectors I<a> and I<b>.

The I<out> parameter describes the resulting vector.


=head2 BH_Vec3iMax

 void BH_Vec3iMax(const int a[3],
                  const int b[3],
                  int out[3]);

Calculates the element-wise maximum of two vectors I<a> and I<b>.

The I<out> parameter describes the resulting vector.


=head1 SEE ALSO

L<BH>
