=encoding UTF-8


=head1 НАИМЕНОВАНИЕ

BH_Box2f - двухмерный ограничивающий прямоугольник


=head1 СИНТАКСИС

 #include <BH/Math/Box2f.h>

 cc prog.c -o prog -lbh


=head1 ОПИСАНИЕ

Модуль BH_Box2f предоставляет функции для работы с двухмерными ограничивающими 
прямоугольниками. Он включает в себя операции объединения, пересечения, проверки
вхождения точки в прямоугольник и вычисления ограничивающего прямоугольника по
набору точек.


=head1 API ВЫЗОВЫ


=head2 BH_Box2fUnion

 void BH_Box2fUnion(const float aMin[2],
                    const float aMax[2],
                    const float bMin[2],
                    const float bMax[2],
                    float outMin[2],
                    float outMax[2]);

Объединяет два ограничивающих прямоугольника A и B.

Параметры I<aMin> и I<aMax> описывают ограничивающий прямоугольник A.

Параметры I<bMin> и I<bMax> описывают ограничивающий прямоугольник B.

Параметры I<outMin> и I<outMax> описывают результирующий ограничивающий 
прямоугольник.


=head2 BH_Box2fIntersect

 int BH_Box2fIntersect(const float aMin[2],
                       const float aMax[2],
                       const float bMin[2],
                       const float bMax[2],
                       float outMin[2],
                       float outMax[2]);

Вычисляет пересечение двух ограничивающих прямоугольников A и B.

Параметры I<aMin> и I<aMax> описывают ограничивающий прямоугольник A.

Параметры I<bMin> и I<bMax> описывают ограничивающий прямоугольник B.

Параметры I<outMin> и I<outMax> описывают результирующий ограничивающий 
прямоугольник.

Возвращает 0 в случае успешного пересечения или код ошибки.


=head2 BH_Box2fContains

 int BH_Box2fContains(const float aMin[2],
                      const float aMax[2],
                      const float point[2]);

Проверяет, находится ли точка I<point> внутри ограничивающего прямоугольника.

Параметры I<aMin> и I<aMax> описывают ограничивающий прямоугольник.

Параметр I<point> описывает точку.

Возвращает 0, если точка находится внутри прямоугольника, или код ошибки.


=head2 BH_Box2fEnclose

 int BH_Box2fEnclose(const float *points,
                     size_t size,
                     float outMin[2],
                     float outMax[2]);

Вычисляет ограничивающий прямоугольник по заданным точкам I<points>.

Параметры I<points> и I<size> описывают входной массив точек.

Параметры I<outMin> и I<outMax> описывают результирующий ограничивающий 
прямоугольник.

Возвращает 0 в случае успешного вычисления или код ошибки.


=head1 СМ. ТАКЖЕ

L<BH>,
L<BH_Box3f>
