=encoding UTF-8


=head1 НАЗВАНИЕ

BH_Timer - утилиты таймера


=head1 СИНТАКСИС

 #include <BH/Timer.h>

 cc prog.c -o prog -lbh


=head1 ОПИСАНИЕ

Этот модуль предоставляет простой интерфейс высокоточного таймера для измерения
прошедшего времени. По возможности таймер использует монотонный источник часов,
что делает его подходящим для точных измерений времени, например, профилирования
или тайм-аутов. Поддерживается точность в миллисекундах и наносекундах; таймер
можно запускать, перезапускать и запрашивать прошедшее время.


=head1 API ВЫЗОВЫ


=head2 BH_TimerNew

 BH_Timer *BH_TimerNew(void);

Создаёт и инициализирует новый объект таймера.

В случае успеха функция возвращает указатель на новый объект BH_Timer,
или NULL в случае ошибки.


=head2 BH_TimerFree

 void BH_TimerFree(BH_Timer *timer);

Уничтожает таймер.


=head2 BH_TimerIsMonotonic

 int BH_TimerIsMonotonic(BH_Timer *timer);

Проверяет, использует ли таймер монотонный источник времени.


=head2 BH_TimerStart

 void BH_TimerStart(BH_Timer *timer);

Запускает или сбрасывает таймер, начиная отсчёт с текущего момента времени.


=head2 BH_TimerRestart

 int64_t BH_TimerRestart(BH_Timer *timer);

Перезапускает таймер и возвращает количество миллисекунд, прошедших с момента
его запуска.


=head2 BH_TimerMilliseconds

 int64_t BH_TimerMilliseconds(BH_Timer *timer);

Возвращает количество миллисекунд, прошедших с момента запуска таймера.


=head2 BH_TimerNanoseconds

 int64_t BH_TimerNanoseconds(BH_Timer *timer);

Возвращает количество наносекунд, прошедших с момента запуска таймера.


=head1 СМ. ТАКЖЕ

L<BH>
