=encoding UTF-8


=head1 НАИМЕНОВАНИЕ

BH_Vec2i - двухмерный целочисленный вектор


=head1 СИНТАКСИС

 #include <BH/Math.h>
 
 cc prog.c -o prog -lbh


=head1 ОПИСАНИЕ

Модуль BH_Vec2i предоставляет набор функций для работы с двухмерными 
целочисленными векторами.


=head1 API ВЫЗОВЫ


=head2 BH_Vec2iAdd

 void BH_Vec2iAdd(const int a[2],
                  const int b[2],
                  int out[2]);

Вычисляет сумму двух векторов I<a> и I<b>.

Параметр I<out> описывает результирующий вектор.


=head2 BH_Vec2iSub

 void BH_Vec2iSub(const int a[2],
                  const int b[2],
                  int out[2]);

Вычисляет разность двух векторов I<a> и I<b>.

Параметр I<out> описывает результирующий вектор.


=head2 BH_Vec2iMul

 void BH_Vec2iMul(const int a[2],
                  const int b[2],
                  int out[2]);

Вычисляет результат перемножения двух векторов I<a> и I<b>.

Параметр I<out> описывает результирующий вектор.


=head2 BH_Vec2iScale

 void BH_Vec2iScale(const int a[2],
                    int b,
                    int out[2]);

Вычисляет результат умножения вектора I<a> на значение I<b>.

Параметр I<out> описывает результирующий вектор.


=head2 BH_Vec2iMulAdd

 void BH_Vec2iMulAdd(const int a[2],
                     const int b[2],
                     const int c[2],
                     int out[2]);

Вычисляет результат суммы I<c> и результата перемножения векторов I<a> и I<b>.

Параметр I<out> описывает результирующий вектор.


=head2 BH_Vec2iNegate

 void BH_Vec2iNegate(const int in[2],
                     int out[2]);

Вычисляет противоположный вектор от вектора I<in>.

Параметр I<out> описывает результирующий вектор.


=head2 BH_Vec2iMin

 void BH_Vec2iMin(const int a[2],
                  const int b[2],
                  int out[2]);

Вычисляет поэлементный минимум двух векторов I<a> и I<b>.

Параметр I<out> описывает результирующий вектор.


=head2 BH_Vec2iMax

 void BH_Vec2iMax(const int a[2],
                  const int b[2],
                  int out[2]);

Вычисляет поэлементный максимум двух векторов I<a> и I<b>.

Параметр I<out> описывает результирующий вектор.


=head1 СМ. ТАКЖЕ

L<BH>
